services:
  node-app:
    build:
      context: .
      target: base
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
